### ISSUE TITLE
Fix automated updates

### ISSUE THREAD

**Issue by Wouter0100** [Petertjuh360/da-letsencrypt#10]
Currently the detecting and updating of the plugin through the automated way in Directadmin isn't working. We need to create a small script which provides the last version (just in txt) through HTTP. This URL has to be set in the `version_url` option in `plugin.conf`. Detection could be done using `https://github.com/Petertjuh360/da-letsencrypt/releases/latest` URL of Github, which returns a header `Location` with the latest version in it.

On the other side we need to create a script which downloads the last release from Github, packs it so Directadmin understands it (.tar.gz), and sends it to the browser. This URL has to be set to the `update_url` in the `plugin.conf`.

**Comment by zenire** [comment]
Can we host this on GitHub or must it be off GitHub? I can host the files if needed.

**Comment by Wouter0100** [comment]
To automate it would be awesome to create something off Github (PHP).

**Comment by zenire** [comment]
Haha, true! I can create them so you can focus on the plugin itself, if you want to?

**Comment by AramVK** [comment]
A complete package without composer could also be a good idea; building all dependencies takes quite a while I've noticed.

**Comment by Wouter0100** [comment]
Yeah, currently thats only once (during install, which is, yeah, an install), so I didn't through that was a big problem. But, you have a point there. Maybe we can run `composer install` when creating the tar.gz for `update_url`

**Comment by barryvdh** [comment]
What about creating a seperate 'build' branch/repo?
You can just point to a Github branch; https://github.com/Petertjuh360/da-letsencrypt/archive/master.tar.gz or release.
Or just commit the vendor files, so you don't need to run composer install?
(Not sure about about how Directadmin plugins updated, if the folder structure matches the update format)

**Comment by Wouter0100** [comment]
The whole idea of composer is not to commit vendor files, hehe :p. But, unfortunately that format doesn't match DirectAdmin's required format. In the root of the tar.gz the files has to be, now there is 1 folder within the root which contains all files.

**Comment by zenire** [comment]
We can create a script to fix the composer install/update with a hook/trigger.

I think we should not deliver the vendor files with our plugin, but include the install/update process/functionality in the plugin. Most of the servers are in a datacenter and has ability to use a fast internet connection and have fast processors.

**Comment by barryvdh** [comment]
You could, but packing the vendor files in the archive will probably always be faster.
You could create a cron that checks the releases, runs composer install/update, creates the archive, commit them in gh-pages branch so you can use Github Pages as simple hosting?

**Comment by AramVK** [comment]
Composer is just really, really slow, it would be not very efficient use of time and resources to go through that process on all the servers that will install this.

I just ran a test; it's a normal/fast VPS; the main thing is that the server during this process is hardly doing anything

`rm -rf vendor/`
`date && composer install && date`

```
Thu Dec 10 12:13:18 CET 2015

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing amphp/amp (dev-master 7268308)
    Cloning 72683085c53e482b294674d9af6e003ffdc4570d

  - Installing amphp/cache (v0.1.0)
    Downloading: 100%

  - Installing amphp/file (dev-master fe2387b)
    Cloning fe2387bb218ecfce236291d4a46b0eb3d23ee887

  - Installing daverandom/libdns (1.0.x-dev e935e8c)
    Cloning e935e8caa5ff30122bcbeb8b4ce567fa14cdf063

  - Installing amphp/dns (v0.8.4)
    Downloading: 100%

  - Installing amphp/socket (v0.9.3)
    Downloading: 100%

  - Installing phpseclib/phpseclib (1.0.0)
    Downloading: 100%

  - Installing sabre/uri (1.0.1)
    Downloading: 100%

  - Installing namshi/jose (6.0.3)
    Downloading: 100%

  - Installing amphp/artax (2.x-dev f0d174a)
    Cloning f0d174ad0b42a6f619fdccfcb99a3059b90e5acc

  - Installing wouter0100/acme (dev-master d356693)
    Cloning d356693e6719d5a44c9d0b4ba0521ad84869f55b

amphp/cache suggests installing amphp/redis (For redis cache driver support)
phpseclib/phpseclib suggests installing ext-gmp (Install the GMP (GNU Multiple Precision) extension in order to speed up arbitrary precision integer arithmetic operations.)
phpseclib/phpseclib suggests installing pear-pear/PHP_Compat (Install PHP_Compat to get phpseclib working on PHP < 5.0.0.)
Generating autoload files

Thu Dec 10 12:18:52 CET 2015
```

Now it took 5 minutes, I've seen it go faster.. but the files in total are only 10MB, that's downloaded and extracted within a few seconds if it's in one package.

**Comment by zenire** [comment]
I agree with you @barryvdh . Let's create another repo to run composer in that repo and deliver the needed files in an archive.

Should we use a cron, another plugin of the install/update function of this plugin to install and update the other repo?

I will create the other repo with a cron to install/update and package the files.

**Comment by zenire** [comment]
Thank you for the feedback @barryvdh and @AramVK , we will deliver the "pre-compiled" files in an archive.

**Comment by barryvdh** [comment]
You don't have to create a new repo, you could just use the gh-pages branch in this one to store the archives.

**Comment by zenire** [comment]
Thank you, will do that.

**Comment by Wouter0100** [comment]
Isn't it better to just use a script to do this? Not just a repo? 

A script which runs every x minutes which retrives the latest version from Github, loads composer, and creates a package. Then we're just able to serve static files.

**Comment by Wouter0100** [comment]
I was already working on this in the "version"-branch.

**Comment by zenire** [comment]
@Wouter0100 Are you talking about the plugin itself or the /vendor/ discussion, or both?

**Comment by Wouter0100** [comment]
Updating the plugin for DirectAdmin and delivering the vendor folders with the updates and install, so there is not need to run `composer install`.

**Comment by zenire** [comment]
Let's continue that development.

**Comment by AramVK** [comment]
You could indeed use https://pages.github.com/ - Project site to store the archive. That way you could have http://petertjuh360.github.io/da-letsencrypt/archive.tar.gz and maybe a page with install instructions or something.

**Comment by Wouter0100** [comment]
[this](https://github.com/Petertjuh360/da-letsencrypt/blob/438b2d5d06afdab1a0b28206357e496644890c3e/src/cron.php) file does everything what we need to do. We're even able to serve very fast, static files. I'm currently building it even loads composer. :+1:

**Comment by Wouter0100** [comment]
Added installing of dependencies through composer in [this](https://github.com/Petertjuh360/da-letsencrypt/blob/b298d4e6410c46d9d485e46f5be6ccd6b8968f54/src/cron.php) file. It works now :+1:

**Comment by Wouter0100** [comment]
Is somebody ( @Petertjuh360 ) able to host that file and run the cron every x seconds? I can host it to, but my domain will properly change in some months due some plans (and this should not be changed.. ever, in the best situation :'P)

**Comment by Wouter0100** [comment]
Or, we could (if possible) automaticly push it to the gh-pages branch, when a new version is out. In that case, it doesn't matter where the script is hosted.

**Comment by barryvdh** [comment]
Just create a simple shell script to remove old file, run php build script, copy the archive to your repo on the gh-pages branch and run `git commit + push` to Github Pages.

**Comment by Wouter0100** [comment]
@barryvdh Hmm, yeah.. Good idea. I'll create a shell script for that :smile:

**Comment by Wouter0100** [comment]
Shell script is created. I will continue on this in it tonight. But if somebody else want to continue, PR is always welcome :+1: . Thx!

**Comment by Wouter0100** [comment]
Pushing to repo also works. See gh-pages branch and my last commit :smile:. The only thing left to do is to let the script check if there is a new version, if not, don't do anything, cuz it's not needed.

**Comment by Wouter0100** [comment]
Hmm, I move some logic from the PHP script to the shell script, just because it's easier to maintain in Shell (for example composer, it isn't meant to be used like this :'p)

**Comment by zenire** [comment]
@Wouter0100 Is hosting still needed or solved with Github pages?

**Comment by Wouter0100** [comment]
Hosting is solved, but the script needs to run every hour or so. Could also be done through a shared webhosting, I should be able to solve this, or if you want it to

**Comment by barryvdh** [comment]
Well, you woud only really need to run it after a new release, right? Not sure how often that is, but you could consider doing that manually, after tagging a new release.

**Comment by Wouter0100** [comment]
Yeah, that should be okay to, hehe.

**Comment by Wouter0100** [comment]
Script is created, this issue is implemented. We'll see how it's going the on the first release :+1:. Thx for helping all!

**Comment by barryvdh** [comment]
It would perhaps be nice to also have a `nightly` or `dev` release, so we can easily test the build and latest version?

**Comment by Wouter0100** [comment]
We should use the pre-release option for that within Github. I'm unsure how the current script handles that tho.

**Comment by barryvdh** [comment]
You could have a modified script that downloads the https://github.com/Petertjuh360/da-letsencrypt/archive/master.zip instead of a release.
