### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by barryvdh** [Petertjuh360/da-letsencrypt#11]
Can you add a status and/or roadmap and a simple 'get started' section?

Can I just clone this folder, run composer install, zip the folder and install via DirectAdmin plugin manager?

Status, what is working, what isn't?
- [x] Creating certificate request
- [x] Accept and automate http challenge in public_html folder
- [x] Install certificate for user?
- [x] Issue cron
- [x] Configuration (API server)

And it's still pointing to staging, right?

**Comment by Wouter0100** [comment]
Default it's still pointing to staging, yes. We have made a [milestone](https://github.com/Petertjuh360/da-letsencrypt/milestones/1.0), there you're able to see the current status.

This isn't everything tho. I will create some issues for the things that needs to be done before the release.

**Comment by zenire** [comment]
A messy get started is now in the README file. It isn't tested and it is not the way a DirectAdmin plugin should be installed, update or used.

8278d33

**Comment by Wouter0100** [comment]
First release is nearby ready. Only the 2 leftover issues, which are both related to the configuration of the ACME server. I'll implement these when I'm back from a good night of sleep :smile:

**Comment by Wouter0100** [comment]
Everything is implemented.

**Comment by barryvdh** [comment]
Initial testing looks good :) Thanks for the great work!
