### ISSUE TITLE
Multi Domain (SAN) Certificates

### ISSUE THREAD

**Issue by sjerdo** [Petertjuh360/da-letsencrypt#13]
You should be able to select which hostnames are to be included in the certificate.

For example:
I have a domain example.com which has subdomains subdomain1 and subdomain2. I have another domain example.net which is a pointer (alias) for example.com

In this case, the following hostnames can/should be included in the certificate example.com:
- example.com
- www.example.com
- subdomain1.example.com
- www.subdomain1.example.com
- subdomain2.example.com
- www.subdomain2.example.com
- example.net
- www.example.net
- subdomain1.example.net
- www.subdomain1.example.net
- subdomain2.example.net
- www.subdomain2.example.net

**Comment by Wouter0100** [comment]
Are SAN certificates supported by Let's Encrypt at all (except `www`)?

**Comment by Wouter0100** [comment]
Hmm, I see. I'll take a look into this. Thanks. Also www is not added by default, I see.

**Comment by Wouter0100** [comment]
Implemented. Thx.
