### ISSUE TITLE
Update user index with more details

### ISSUE THREAD

**Issue by Wouter0100** [Petertjuh360/da-letsencrypt#14]
Currently, you're only able to request a SSL certificate through this page. Here we should add the another page for when the SSL certificate is active, with more details like expiry date and a reissue button. At the moment, the user doesn't have a clue when it expires or if it's even installed.

**Comment by zenire** [comment]
What about splitting it in a few pages:
1. Index with the information
2. Request page for requesting and installing certificates
3. Keys page with the keys (optional)

**Comment by Wouter0100** [comment]
Hmm, yeah. That would be good. On page 3 we should display his account keys, then, with a link to the SSL certificates page of Directadmin for the SSL certificate keys.

**Comment by zenire** [comment]
I agree

**Comment by Wouter0100** [comment]
Implemented
