### ISSUE TITLE
Add delete options

### ISSUE THREAD

**Issue by Wouter0100** [Petertjuh360/da-letsencrypt#15]
Delete options for domain and account. When account delete button has been pressed, we will wipe everything and the domain will not be monitored anymore. When domain delete button has been pressed, we will only wipe the domain.

Shall we also disable the SSL and CA certificates in DirectAdmin?

**Comment by Wupgup** [comment]
Why wouldn't you remove the SSL and CA certificates? The domain isn't monitored anymore and if the users adds it again you'll create new certificates anyway.

**Comment by Wouter0100** [comment]
We're unable to remove them (because DirectAdmin doesn't let us do so), but we could disable them. You have a point there tho. I'll get this implemented asap.

**Comment by Wouter0100** [comment]
Implemented.
