### ISSUE TITLE
SAN domains not in certificate 

### ISSUE THREAD

**Issue by Wouter0100** [Petertjuh360/da-letsencrypt#18]
I've recently found out that SAN certificates are not properly handled at Let's Encrypt (as it seems like). I'm unsure why, the CSR seems to be correct and holds all necessary information.

See [this](https://gist.github.com/Wouter0100/14e023ac5c36ef434a11) CSR at [this](https://certlogik.com/decoder/) or [this](https://www.networking4all.com/en/support/tools/csr+check/) site.  This CSR is created using our plugin.

After sending this CSR to Let's Encrypt and after receiving the cert, it doesn't seems to contain the SAN domains. Only the domain provided in the CN field (which wasn't there in the example CSR, I was testing around).

I'm not sure if this is the right location to post it tho, because it has something to do with the library I think. But I hope one of you guys know what's going wrong.

**Comment by zenire** [comment]
Could you try it with filling in "O" (because the site says "O = Unknown")

**Comment by Wouter0100** [comment]
That's the value set by the CSR ([see here](https://github.com/Wouter0100/acme/blob/master/lib/AcmeService.php#L173))

**Comment by Wouter0100** [comment]
Hmm, I think I found the issue. We don't do challenges for the subdomains, only the domain.

**Comment by AramVK** [comment]
Trying to figure out what possibilities you have:
- DA default is: domain.tld  + www.domain.tld
- DirectAdmin type subdomain root in public_html/subdomain
- Alias pointer

I don't think the subdomain type can get SSL, you simply can't configure it?

The alias pointer is possible, it will use the main certificate so I guess a list of alias pointer is needed.

Maybe through API? http://www.directadmin.com/features.php?id=382

**Comment by Wouter0100** [comment]
If I'm correct, the HTTPS certificate is applied to the domain and all it's subdomains. So for SAN certificates (which validates multiple domains) this is ideal.

**Comment by sjerdo** [comment]
> If I'm correct, the HTTPS certificate is applied to the domain and all it's subdomains. So for SAN certificates (which validates multiple domains) this is ideal.

You are correct. The certificate is applied to the domain, the subdomains and the aliases + subdomains.

**Comment by Wouter0100** [comment]
I've implemented the challenges for all subdomains (using a bit nasty workaround tho), but it doesn't seems to work yet. I'm unsure why. All challenges seems to succeed.

**Comment by Wouter0100** [comment]
It seems to be resolved, I'm unsure why, but https://dev.wouter0100.nl and https://www.dev.wouter0100.nl are now included in the certificate. I think the subdomain challenges worked, but didn't test it good enough or something.

Can someone confirm the working of the SAN certificates using the latest commit (92da67ef1cd0fc5226fa12efb3464ad9860d5b8c)?

**Comment by ghost** [comment]
@Wouter0100 

It seems resolved :+1: 

Tested it on a DA box with a random domain, both domain + www.domain are in the certificate now.

**Comment by zenire** [comment]
It is working here too

**Comment by Wouter0100** [comment]
Good to hear, then this issue is solved.
