### ISSUE TITLE
Sometimes invalid nonce

### ISSUE THREAD

**Issue by barryvdh** [Petertjuh360/da-letsencrypt#25]
Sometimes I get an error when requesting the certificates:

> Invalid response code: 400 {"type":"urn:acme:error:badNonce","detail":"Unable to read/verify body :: JWS has invalid anti-replay nonce","status":400}

Not sure how this happens. Sometimes it does, sometimes it doesn't. It worked fine yesterday on live server, today got this error a few times on staging.

**Comment by kelunik** [comment]
See https://github.com/letsencrypt/boulder/issues/1217. We have to log all nonces to find the actual error.

**Comment by Wouter0100** [comment]
Hmm, it may because of a functionality which isn't properly ported in the library. I'm not sure if it's in your library also, or do you see the same issue outside the plugin?

**Comment by barryvdh** [comment]
The linked issue was from before mine, so I'm guessing it's an upstream issue. Not this DA plugin and not your port.

**Comment by kelunik** [comment]
It's either a boulder issue or an issue in my library.

**Comment by Wouter0100** [comment]
Hmm, okay. I'm going to try to debug this in some days. Not sure how though.

**Comment by kelunik** [comment]
I think we should resend requests with a `badNonce` error, shouldn't we?
