### ISSUE TITLE
Cron questions/issues

### ISSUE THREAD

**Issue by barryvdh** [Petertjuh360/da-letsencrypt#26]
A few notes about the cron:
- When the plugin is installed but not active, does the cron still run? Should a check in the beginning of cron.php check whether the plugin is active, and otherwise directly quit?
- When no certificates are renewed, should a message still be sent? Or perhaps with a different header? Or add the number of renewals in the subject header?
- 2 messages in my case 2 tickets were merged together; see image:

![image](https://cloud.githubusercontent.com/assets/973269/11805687/2b257d94-a30e-11e5-80e2-0b13cd6c6eb1.png)

**Comment by barryvdh** [comment]
And when no certificates changed, no need to rewrite/reload the webservice.

**Comment by Wouter0100** [comment]
True the rewrite/reload. Isn't there a way to say to DirectAdmin which HTTPD config he needs to rewrite? Currently we do always all configs at the end of the cron, which isn't ideal. Indeed. Number of renewals in the header seems to be a good idea. I don't think not sending these notifications when no item is renewed isn't a good idea, maybe something went wrong and nobody will know.

**Comment by zenire** [comment]
As far as I know there is only a command to rewrite all HTTPD config files via DirectAdmin.

When no certificates are renewed we should sent a message with something like: "The reissue cron just ran but there are no certificates to renew."

**Comment by barryvdh** [comment]
Another cron issue; subdomains aren't processed I think?

``` php
 try {
            $challenges = new Challenges($domain);
            $challenges->solveChallenge();

            $log->log('Successfully completed challenge for ' . $domain->getDomain());
...
```

**Comment by Wouter0100** [comment]
It seems like. I need to do a full rewrite of the subdomain and domain logic, I think. Currently the challenges are a bit nesty, if you ask me.

**Comment by zenire** [comment]
We will have to rewrite all configs because of the lack of function to rewrite the files of a single user in DirectAdmin.

**Comment by Wouter0100** [comment]
Hmm, I'll send that as a request to John. Maybe he's able to implement that. But in the meanwhile, I don't think we need to rewrite every cron run, only when something did change.

**Comment by sjerdo** [comment]
In [line 81](https://github.com/petertjuh360/da-letsencrypt/blob/master/scripts/cron.php#L81) the subdomains are fetched from the config and included in the CSR. Seems correct. But, in [line 90](https://github.com/petertjuh360/da-letsencrypt/blob/master/scripts/cron.php#L90) subdomains in the config is set to all the subdomains for the domain (so not just the ones selected). So next time the cron will run, it'll try to include all the subdomains in the certificate.

You should also change `$challenges = new Challenges($domain);` to `$challenges = new Challenges($domain, $domain->config('subdomains'));` to fix the cron. Currently the subdomains aren't even included in the challenges.

**Comment by zenire** [comment]
I implemented your fix to include the subdomains. I sugges to close this issue and open new issues because there are multiple discussions/problems in this issue.

**Comment by Wouter0100** [comment]
I've mailed DirectAdmin support about this notification issue. I hope there is a script available (or, something..) to send a notification.

**Comment by Wouter0100** [comment]
John did some great work here :-). He added a way of sending messages to the Message System. 

https://www.directadmin.com/features.php?id=1829
