### ISSUE TITLE
User in plugin.conf not used

### ISSUE THREAD

**Issue by zenire** [Petertjuh360/da-letsencrypt#28]
Is `user` used in `plugin.conf` ? Seems that this was added because of enabling the plugin per user level but this is obsolete since issue #3

**Comment by Wouter0100** [comment]
Nope, ins't used anymore.

**Comment by zenire** [comment]
Okay, I will remove it. Thank you!

**Comment by Petertjuh360** [comment]
Okay, I will remove it. Thank you!
