### ISSUE TITLE
No permission to execute composer

### ISSUE THREAD

**Issue by zenire** [Petertjuh360/da-letsencrypt#30]
Hi,

I am getting the following error when running `/scripts/install.sh` on CentOS 6:

> [root@server3 da-letsencrypt]# sh ./scripts/install.sh
> ./scripts/install.sh: regel 12: /tmp/composer.phar: Toegang geweigerd
> Successfully installed Let's Encrypt plugin to DirectAdmin.

"Toegang geweigerd" means "No permission"

**Comment by zenire** [comment]
Only the user `root` has permission to execute files in /tmp. Should we create an own temporary folder?

**Comment by barryvdh** [comment]
As I said earlier, why do you need the /tmp folder? Just download the composer.phar in the plugin folder.
And anyways, a user installing the release doesn't need composer, right?

**Comment by zenire** [comment]
You are right, an user installing the release does not need composer. It would also be possible to just download it in the plugin folder.

Do we need to include the composer install/update function in our package? If we deliver the vendor files we could just remove the composer install/update function even in the current way it is implemented (only execute when /vendor is not present).

**Comment by barryvdh** [comment]
I would remove it from install.sh, as it's only required when installing from git. Then just use the readme.

**Comment by zenire** [comment]
I agree with you. I will remove it if @Wouter0100 also agrees. What is your opinion, Wouter?

**Comment by zenire** [comment]
@Wouter0100 Could you take a look at this, so we can solve this issue, please? Thanks in advance!

**Comment by Wouter0100** [comment]
Hmm, okay. I'll agree with this!

**Comment by zenire** [comment]
Thank you, I will remove the code and solve this issue.

**Comment by zenire** [comment]
Code removed, issue solved.

**Comment by Wouter0100** [comment]
But, normally everyone (1777) has access to `/tmp`, so I do think there is also something wrong with your server setup.

**Comment by zenire** [comment]
Yes, it is fixed now, but there are many servers which also have wrong settings for /tmp

**Comment by Wouter0100** [comment]
Hmm, strange. Never seen that before here, but yeah.. Some people/servers do weird things. :'P

**Comment by ictabc** [comment]
See http://help.directadmin.com/item.php?id=247

So not so strange that an executable is not allowed to run from /tmp. Basic security principles

**Comment by Wouter0100** [comment]
Hmm, good point! I didn't think of the execute, only R/W. Thx @ictabc
