### ISSUE TITLE
Replace fork with original kelunik/acme

### ISSUE THREAD

**Issue by barryvdh** [Petertjuh360/da-letsencrypt#32]
Just to keep track of the issue, as discussed in #22, https://github.com/kelunik/acme is now PHP5.5+ so the fork is no longer needed.

**Comment by Wouter0100** [comment]
Thx for creating this one. Good reminder that this has to be done. :+1:

**Comment by Wouter0100** [comment]
Started to implement this, unfortunately I came across [this](https://github.com/kelunik/acme/pull/5) issue.

**Comment by Wouter0100** [comment]
Fully working :+1:
