### ISSUE TITLE
Detect DirectAdmin port

### ISSUE THREAD

**Issue by Wouter0100** [Petertjuh360/da-letsencrypt#34]
Some users may not use the default port 2222 for DirectAdmin. We've to detect this and use the detected port for API calls.

**Comment by zenire** [comment]
Check `port` parameter in `/usr/local/directadmin/conf/directadmin.conf`

**Comment by Wouter0100** [comment]
Do all users have read access to that config file? I don't think so. We could use the request URL, but there isn't any in the cron. But, the cron does have access to that file

**Comment by zenire** [comment]
Only DirectAdmin has access to the directadmin.conf, but this parameter specifies the port for all users. We could detect and set this port in our plugin when installing the plugin?

**Comment by Wouter0100** [comment]
I also thought that may be a solution, but I don't think so. When the port is being changed, this is a real thing to forget.

We could create 2 scenario's:
- When an user (non-root/non-diradmin) sends an API request, parse the port from the `$_SERVER['REQUEST_URL']`.
- When an cron (root/diradmin) sends an API request, parse the `directadmin.conf` for the port.

**Comment by phillcoxon** [comment]
I've just installed da-letsencrypt and hit this exact problem as I don't have DA running on the default port. 

Very happy to help test any proposed solutions.

**Comment by zenire** [comment]
I think the cron solution is the best solution. This way it is more reliable. The downside it is less user friendly. With the current cron the change will have effect after a month.

We could solve this with running the cron more frequently or creating another cron.

However it wouldn't be a problem for me personally to set the DirectAdmin port in the plugin config file manually. When you change the DirectAdmin port you will need to change `directadmin.conf` and `/var/www/html/redirect.php` anyways.

**Comment by Wouter0100** [comment]
Why would you create a cron for that? We don't need to save the port at all.

**Comment by zenire** [comment]
Excuse me, I didn't understand you.
