### ISSUE TITLE
Always use API? (also in cron)

### ISSUE THREAD

**Issue by barryvdh** [Petertjuh360/da-letsencrypt#35]
Wouldn't it be better to always use the API?

Not sure if it's possible, but right now there 2 ways to get all subdomains, two ways to add certificates etc. It would probably be more 'reliable' when it's just the API.

Problems:
- Currently API is using the user session, no password/keys
- Cron doesn't have user session/context

Possible solutions:
- Use admin login key (restrict usage to local IP and SSL+actual commands), use that to login as client (admin|user), but not sure if that's possible with login keys.
- Create and store login keys per user, use that to login as the actual user.
- (Could be created via the API, without user interaction)

Downsides of login keys
- More work maintaining/syncing them? But already is a config system for certs/keys etc.
- Security? Should be okay becase you can restrict per IP and commands, right?

**Comment by Wouter0100** [comment]
Personally I don't have any experience with login keys. I don't think it's very user friendly when we create a login key, because then it will be also visible in the login keys list. Maybe a admin login key could work, but then we need to switch between users, as you mentioned.

**Comment by zenire** [comment]
A login key needs to be created manually as far as I know. It is a bit more work to setup but it is more reliable and more safe.

I don't think we should create login keys per user, but only for an admin because otherwise we would need to create a login key for each user manually.

I am not very sure if it isn't possible to create login keys with the DirectAdmin API but I couldn't find this function on the DirectAdmin site.

**Comment by Wouter0100** [comment]
Hmm, login keys could also be disabled..

**Comment by barryvdh** [comment]
They could indeed be disabled (but enabled by default). It does seem possible with the API:
http://www.directadmin.com/features.php?id=1298

> The api version: CMD_API_LOGIN_KEYS is fully implemented (see the html forms for details)

**Comment by Wouter0100** [comment]
Hmm, @Petertjuh360 just installed a VPS where login keys are disabled. I also don't think it would be good to require this.

It would solve a lot of problems (where we need to manipulate files/things manually) though.

**Comment by Wouter0100** [comment]
I'm currently building this feature. I had something like this in mind, where the details are written to a write-only file. After that, the details can be read from the cron (root) to execute API requests. 

When the cron isn't able to find/read the details, we could send a notification through the Message System. :)

![screenshot from 2016-01-22 09 58 39](https://cloud.githubusercontent.com/assets/864520/12506365/bcc45aec-c0ee-11e5-8302-5ade9633813d.png)

**Comment by barryvdh** [comment]
Is there a valid reason not to enable login keys on your server?
Can't we just make it a requirement to use this plugin. Seems safer/easier than storing the admin credentials.

**Comment by Wouter0100** [comment]
Hmm, that's true. It was an example how I had it in mind. Is there a difference between a login key and the credentials? When someone has the key, he's still able to do anything, isn't he?

**Comment by barryvdh** [comment]
Not in my understanding. I would think that workflow would be like this:
1. Use the admin account from session in the API to create a loginkey for letsencrypt (CMD_API_LOGIN_KEYS)
2. Only ask for localhost access, unlimited requests, no expiry and just the commands that we need (CMD_API_SSL and ..?).
3. Store the keys somewhere and use that in the cron.

See /CMD_LOGIN_KEYS page as admin, which lists all the APIs (more below the scroll)
![screen shot 2016-01-22 at 10 29 23](https://cloud.githubusercontent.com/assets/973269/12507002/43386ef2-c0f3-11e5-9cab-9912da13533b.png)

If someone reads that key, all they can do is call the SSL API from localhost. While full admin credentials would be able to do _anything_

**Comment by Wouter0100** [comment]
Oeh. Is wasn't known yet with Login Keys. I thought they were just a "API key" without restrictions. This seems really useful and it would make sense to require that, indeed. I'll take a look into that :).

**Comment by Wouter0100** [comment]
I'd like to move this conversation to #75 since there is a open PR :)
