### ISSUE TITLE
/actions/request.html white page

### ISSUE THREAD

**Issue by henkque** [Petertjuh360/da-letsencrypt#37]
After accepting the terms for LE, request.html only shows a empty white page in DirectAdmin layout. 

The LE account looks succesfull created since I can view the keys for a account. 

The SSL cert itself is not created.

Unfortanatly no errors in the php error log.

System: Centos 5, up to date directadmin.

**Comment by Wouter0100** [comment]
Which PHP error log are you looking at? Our plugin's PHP error log is located at `/usr/local/directadmin/plugins/da-letsencrypt/logs/php-error.log`. White page issues should be related to a PHP error.

**Comment by henkque** [comment]
Yes, in /usr/local/directadmin/plugins/da-letsencrypt/logs/php-error.log

**Comment by zenire** [comment]
Did you run `composer install` ?

**Comment by zenire** [comment]
The commands to install the plugin were not showed correctly in the README.md file. Could you run those commands again, please?

**Comment by henkque** [comment]
Yes, I did. It created the "vendor" folder. I followed the instructions
from the readme file. Ik already find out that something went wrong and
installed composer manual. Ill going to try to run these commands

I do have a error in the log file now.
19-Dec-2015 01:30:01 Europe/Brussels] PHP Parse error:  syntax error,
unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \
(T_NS_SEPARATOR) in
/usr/local/directadmin/plugins/da-letsencrypt/vendor/wouter0100/acme/lib/AcmeService.php
on line 8

Did you run composer install ?

**Comment by zenire** [comment]
@Wouter0100  Could this be related to #32  ?

**Comment by henkque** [comment]
Please note that this error not returned when generating a ssl cert on request.html. I think this error and the white page are two different problems

**Comment by Wouter0100** [comment]
The composer.lock contains the wrong commit from my repo, that's why people receive these errors. It will be fixed when we switch to kelunik's repo.

**Comment by Wouter0100** [comment]
Could you please try using the latest commit and a `composer install`?
