### ISSUE TITLE
Test for SNI when installing

### ISSUE THREAD

**Issue by Wouter0100** [Petertjuh360/da-letsencrypt#38]
SNI must be enabled for this plugin to properly with, because DirectAdmin will prevent API calls from being made when SNI isn't enabled (or the user must have an own IP).

**Comment by zenire** [comment]
Should we give the admin a warning or just enable SNI automatically?

**Comment by Wouter0100** [comment]
If you ask me, the installation should fail when SNI isn't enabled.

**Comment by zenire** [comment]
I agree
