### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by Edgy1337** [Petertjuh360/da-letsencrypt#42]
[root@server da-letsencrypt]# composer install
-bash: composer: command not found

and when i install with directadmin plugin manager i get this error when it is activated.

Warning: require_once(/usr/local/directadmin/plugins/da-letsencrypt/vendor/autoload.php): failed to open stream: No such file or directory in /usr/local/directadmin/plugins/da-letsencrypt/includes/bootstrap.php on line 7 Fatal error: require_once(): Failed opening required '/usr/local/directadmin/plugins/da-letsencrypt/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /usr/local/directadmin/plugins/da-letsencrypt/includes/bootstrap.php on line 7

**Comment by zenire** [comment]
Run the following commands and try again, please:

`curl -sS https://getcomposer.org/installer | php`  
`composer install`  

You don't have composer installed. When we release the plugin we will provide the vendor files in the plugin.

**Comment by Edgy1337** [comment]
Already run,
Still doesnt work :(

**Comment by Edgy1337** [comment]
For other people run this command php composer.phar install
That fixed it for me
