### ISSUE TITLE
directadmin/error.log

### ISSUE THREAD

**Issue by jnico** [Petertjuh360/da-letsencrypt#45]
Install goes fine as long as .phar is added to suhosin whitelist and proc_open proc_close and something else (cant recall) is not in php.ini disabled_functions.
Okay for a few days constant logging of error in: /var/log/directadmin/error.log

`Unable to get any data from petertjuh360.github.io:23.xxx.50.xxx : Cannot find the end of the headers<br>`

**Comment by zenire** [comment]
At which command does it fail?

**Comment by jnico** [comment]
I have suhosin compiled so I had to whitelist .phar so composer could install. A warning does come up after running composer install of the requirement, that was easy enough to add..

So if proc_open is in disabled_functions php.ini the when running 'compser install' composer will fail with warning of proc_open, I removed both proc_open and close, there was a complaint about something else after removing those two from php.ini though the error wasn't specific to what was the cause, so I removed everything in disabled_functions just for install, after those small changes install gave the all green light.

Server runs, centos7.2, apache2.4, php-fpm 5.5, Suhosin 9.38, mod_security, csf firewall.

Updating works fine, and certificates install first time, and are removed without error so the plugin simply works, just this odd error line is always popping up in error.log one after the other all day until the plugin was disabled and removed.

The plugin is currently not installed for the moment, though I intend to run it again few days after new years day, well after i recover from a massive hangover. eek.

So all I have concern about it is just the error in log...  perhaps you have seen it before.. if not what do think could be the cause of the error, Im starting to think now it could be mod_security or even csf, but I wont know for sure until after new years, about a week from now. If I dont reply its because I'm already on the road until then.

Cheers
Jon

**Comment by Wouter0100** [comment]
Composer install is just something for a development environment (where there aren't any disabled functions and so on), I don't feel like this is our (current) problem. The plugin will include all it's dependencies when it's released, so no composer required there. 

You could load composer on a local machine and upload it to your server when you require it.

**Comment by Bramzor** [comment]
I'm having the same error in my logfiles:

2016:01:19-10:26:18: Unable to get any data from petertjuh360.github.io:51.255.221.156 : Cannot find the end of the headers<br>

2016:01:19-10:27:32: Unable to get any data from petertjuh360.github.io:51.255.221.156 : Cannot find the end of the headers<br>

2016:01:19-10:29:56: Unable to get any data from petertjuh360.github.io:51.255.221.156 : Cannot find the end of the headers<br>

So I suppose this issue is valid?

**Comment by Bramzor** [comment]
Might it be that Directadmin checks the version_url which gives a 404? http://petertjuh360.github.io/da-letsencrypt/versioning/version

**Comment by Wouter0100** [comment]
You receive these errors because we haven't released any stable version.
