### ISSUE TITLE
httpd restart in cron

### ISSUE THREAD

**Issue by zenire** [Petertjuh360/da-letsencrypt#48]
In the file `/scripts/cron.php` on line 104 the cron will restart httpd gracefully. I am not sure but doesn't the rewrite on line 103 restarts httpd already?

**Comment by Wouter0100** [comment]
Hmm, I wasn't sure about this too. Are you maybe able to run some tests, to test this? If HTTP is restarted when the files are rewritten.

**Comment by zenire** [comment]
I will test it today.

**Comment by zenire** [comment]
The webserver(s) will be restarted when the files are rewrited. A second restart is not necessary so I removed it.
