### ISSUE TITLE
Security enhancement

### ISSUE THREAD

**Issue by zenire** [Petertjuh360/da-letsencrypt#5]
/user/actions/request.html on line 68 shows that if an RSA private key exists, it will be re-used. I believe it is better to generate new keys to prevent abuse from possible stolen keys upon a hack. This way the private key changes every 90 days which improves security.

Correct me if im wrong, please.

**Comment by Wouter0100** [comment]
Hmm, true. Maybe we shouldn't even save the private key to a file?

**Comment by zenire** [comment]
We only need to give the keys to DirectAdmin. There is no usecase to let the plugin store the keys for itself. When there is a problem or when somebody needs a key, it is very easy to request a new one.

**Comment by Wouter0100** [comment]
Hmm, line 68 is for another purpose. These RSA keys generated are for the user, which needs to be saved for the reissue. I've implemented the creation of RSA keys for domains [here](https://github.com/Petertjuh360/da-letsencrypt/commit/c0973d497d8285e05c9220ba8f8f5e23a615fcbb), not saved as mentioned.

**Comment by Wouter0100** [comment]
This issue is fixed.
