### ISSUE TITLE
Compatible with PHP7?

### ISSUE THREAD

**Issue by v998** [Petertjuh360/da-letsencrypt#51]
Just got this PHP Fatal Error on my server.

I guess this is because I am running PHP 7.0...

(I was requesting a Certificate at that time)

![image](https://cloud.githubusercontent.com/assets/7825360/12020169/0e7c52a2-adb4-11e5-9329-378308ef5009.png)

**Comment by Sasiko** [comment]
if u are using opcache, disable it

**Comment by Wouter0100** [comment]
Duplicate of #40
