### ISSUE TITLE
Default RSA key bitlength should be 2048

### ISSUE THREAD

**Issue by alect001** [Petertjuh360/da-letsencrypt#55]
I think 2048bit is enough..2048-bit should be ok until about 2030

**Comment by v998** [comment]
+1
Also the official letscrypt uses 2048, isn't it?

**Comment by zenire** [comment]
Thank you for your comment!
The keys we generate are 4096-bit. This is better then 2048-bit.

**Comment by Wouter0100** [comment]
Hmm, is there any reason to use 2048 instead of 4096?

**Comment by alect001** [comment]
https://www.gnupg.org/faq/gnupg-faq.html#no_default_of_rsa4096 

> A keysize of 2048 is sufficient. Using 4096 "gives us almost nothing, while costing us quite a lot." 
> 
> If you need more security than RSA-2048 offers, the way to go would be to switch to elliptical curve cryptography — not to continue using RSA. 
> 
> 11.6 Why does GnuPG support RSA-4096 if it ’ s such a bad idea? 
> RSA-4096 is not a bad idea: it ’ s just, generally speaking, unnecessary. You gain very little in the way of additional resistance to brute-forcing and cryptanalysis.

**Comment by Wouter0100** [comment]
Thx, I'll update this.

**Comment by zenire** [comment]
I didn't know about the 2048 vs 4096 debate. I agree with using 2048
