### ISSUE TITLE
Can't Request a (new) SSL certificate 

### ISSUE THREAD

**Issue by iPokz** [Petertjuh360/da-letsencrypt#56]
It's show error message : 
###### Error while completing domain challenges

```
Details
Could not obtain directory.
```
# 

OS : CentOS 6 (x64)
DirectAdmin with Custombuild 
Nginx Web Server

**Comment by iPokz** [comment]
###### Error when uncheck Subdomains options

``` php
 Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /usr/local/directadmin/plugins/da-letsencrypt/includes/lib/Domain.php on line 109 
```

but if checked subdomains it work :+1: 

# 

OS : CentOS 6 (x64)
DirectAdmin with Custombuild
Apache 2.2 Web Server

**Comment by Wouter0100** [comment]
Please separate these issues.
