### ISSUE TITLE
Remove `.well-known` directory

### ISSUE THREAD

**Issue by Wouter0100** [Petertjuh360/da-letsencrypt#6]
After a HTTP-01 challenge the `.well-known`-dir in the public_html domain files isn't removed yet.

**Comment by sjerdo** [comment]
The .well-known directory should only be removed if it was created during the validation process. It shouldn't be deleted if it existed before that, while it could be used for other purposes (eg [Digital Asset Links](https://developers.google.com/digital-asset-links/v1/getting-started))

**Comment by Wouter0100** [comment]
Good point, thx.
