### ISSUE TITLE
Problem when installing the plugin

### ISSUE THREAD

**Issue by redjersey** [Petertjuh360/da-letsencrypt#62]
I have php 5.5.31 and have composer installed. When I run:

php composer.phar install

I got the warning saying:

Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

I have tried
php composer.phar update 
or
php composer.phar update --lock

and run the composer install again, and can't get rid of the warning.

should I keep proceeding the command: chown diradmin:diradmin -hR ../da-letsencrypt/ Change active=no and installed=no to active=yes and installed=yes in plugin.conf?

please advise

**Comment by zenire** [comment]
That is no problem. You can run `php composer.phar self-update` to update composer itself and the warning will be gone.

You can proceed with `chown diradmin:diradmin -hR ../da-letsencrypt/`

**Comment by redjersey** [comment]
here is what I got:

php composer.phar self-update
You are already using composer version 764de14b5eb2980ba9d479865b075ef3bf858600.
[root da-letsencrypt]# chown diradmin:diradmin -hR ../da-letsencrypt/
[root da-letsencrypt]# nano plugin.conf
and changed 
active=yes and installed=yes

when I logged in DA and clicked on the da-letsencrypt page I got:

Warning: require_once(/usr/local/directadmin/plugins/da-letsencrypt/vendor/autoload.php): failed to open stream: No such file or directory in /usr/local/directadmin/plugins/da-letsencrypt/includes/bootstrap.php on line 7 Fatal error: require_once(): Failed opening required '/usr/local/directadmin/plugins/da-letsencrypt/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /usr/local/directadmin/plugins/da-letsencrypt/includes/bootstrap.php on line 7

**Comment by Wouter0100** [comment]
The error message from Composer literally says what it meant to be: our composer.lock isn't up-to-date with composer.json. This because it wasn't updated after 93a2eca504b2d7e9d526e3803f84617b9474f75c.

**Comment by barryvdh** [comment]
The warning shouldn't matter much, but you can run 'composer update' to get rid of the warning.

**Comment by zenire** [comment]
`git pull`
`php composer.phar update`
`php composer.phar install`

and proceed

**Comment by redjersey** [comment]
sorry but I'm still having the same error.
[root da-letsencrypt]# git pull
git: /usr/local/lib/libz.so.1: no version information available (required by git)
git: /usr/local/lib/libz.so.1: no version information available (required by git)
git: /usr/local/lib/libz.so.1: no version information available (required by git)
git: /usr/local/lib/libz.so.1: no version information available (required by git)
git: /usr/local/lib/libz.so.1: no version information available (required by git)
git: /usr/local/lib/libz.so.1: no version information available (required by git)
git: /usr/local/lib/libz.so.1: no version information available (required by git)
git: /usr/local/lib/libz.so.1: no version information available (required by git)
git-remote-https: /usr/local/lib/libz.so.1: no version information available (required by git-remote-https)
git: /usr/local/lib/libz.so.1: no version information available (required by git)
git: /usr/local/lib/libz.so.1: no version information available (required by git)
git-merge: /usr/local/lib/libz.so.1: no version information available (required by git-merge)
Already up-to-date.
[root da-letsencrypt]# php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Installing sabre/uri (1.0.1)
  Loading from cache

after that I open the letsencrypt page in directadmin and still getting:

Plugins
Warning: require_once(/usr/local/directadmin/plugins/da-letsencrypt/vendor/autoload.php): failed to open stream: No such file or directory in /usr/local/directadmin/plugins/da-letsencrypt/includes/bootstrap.php on line 7 Fatal error: require_once(): Failed opening required '/usr/local/directadmin/plugins/da-letsencrypt/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /usr/local/directadmin/plugins/da-letsencrypt/includes/bootstrap.php on line 7

it's complaining the missing file autoload.php in vendor folder

**Comment by barryvdh** [comment]
And does the vendor folder exist? With the autoload file? Or is it somewhere else?

**Comment by redjersey** [comment]
the vendor folder exists with 3 sub-folders:
amphp  composer  sabre

it's just the autoload.php is missing.
ie /usr/local/directadmin/plugins/da-letsencrypt/vendor/autoload.php missing

**Comment by kloentje2** [comment]
I just have installed it without a problem. Just ignore the yellow message :D

**Comment by barryvdh** [comment]
And what does `php composer.phar dump-autoload`  do? Or perhaps with more verbosity: `php composer.phar dump-autoload -vvv`

**Comment by redjersey** [comment]
You don't understand kloentje2, I can't just ignore the message in DA CP. includes/bootstrap.php called the autoload.php which doesn't exist and the php stopped executing

**Comment by Wouter0100** [comment]
What do you get when you dump the autoload file manually, like @barryvdh said?

**Comment by redjersey** [comment]
after calling the composer dump-autoload file, it auto generates the autoload.php inside vendor and now if I open the page no error msg shown. thanks :)

**Comment by Wouter0100** [comment]
Good to hear. Strange enough it wasn't dumping the autoload file.. If you've any problems with the module, don't hesitate to open a PR or issue :+1:.

**Comment by comput1q** [comment]
i have the same issue..
DA notifies Warning: require_once(/usr/local/directadmin/plugins/da-letsencrypt/vendor/autoload.php): failed to open stream: No such file or directory in /usr/local/directadmin/plugins/da-letsencrypt/includes/bootstrap.php on line 7 Fatal error: require_once(): Failed opening required '/usr/local/directadmin/plugins/da-letsencrypt/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /usr/local/directadmin/plugins/da-letsencrypt/includes/bootstrap.php on line 7

and if i did update composer...
[root@web01 emin]# php /usr/bin/composer selfupdate
You are already using composer version 42f49b3b979b7039d138e260d9087e93e46d715a.

**Comment by Wouter0100** [comment]
This are issues of Composer. If you're not experienced with Composer, please don't install this plugin yet. When released it won't require experience of anything.

**Comment by comput1q** [comment]
how can i fix this.?

Op 17-1-2016 om 16:11 schreef Wouter van Os:

**Comment by zenire** [comment]
Try to open an issue here: https://github.com/composer/composer/issues

**Comment by barryvdh** [comment]
Die you run composer install? Try 'composer update -vvv' for more output.

**Comment by comput1q** [comment]
can you help me with teamviewer?

Op 17-1-2016 om 19:46 schreef Barry vd. Heuvel:

**Comment by Wouter0100** [comment]
@comput1q, please wait for the stable release. Then you're able to install it without any problems.

**Comment by comput1q** [comment]
can you speak dutch? i think yes

Op 17-1-2016 om 21:29 schreef Wouter van Os:

**Comment by Wouter0100** [comment]
Yes, most people here are dutch, which is quite funny.

**Comment by comput1q** [comment]
Beter, Haha mijn engels is niet zo heel erg goed. Ik zag het al aan je 
naam.. Wanneer komt de stabiele versie uit ongeveer?

Op 17-1-2016 om 21:32 schreef Wouter van Os:

> Yes, most people here are dutch, which is quite funny.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Petertjuh360/da-letsencrypt/issues/62#issuecomment-172378301.
> 
> Geen virus gevonden in dit bericht.
> Gecontroleerd door AVG - www.avg.com http://www.avg.com
> Versie: 2016.0.7303 / Virusdatabase: 4489/11421 - datum van uitgifte: 
> 01/17/16

---- Translated to English by @Petertjuh360 -----

That is better, my English is not very good haha. I already saw you're Dutch by your name. When will the stable version be released?

**Comment by zenire** [comment]
@comput1q The stable version will be releases when all issues tagged with milestone 1.0 are solved. This is an opensource project and everyone who wants to help can help to solve those issues and improve the plugin.

Badly enough there is not always enough time or knowledge to solve each issue fast.

So in short: We don't know, depens on the help of others and free time.

**Comment by Wouter0100** [comment]
We currently don't know when a stable version is released.

**Comment by comput1q** [comment]
als ik zou kunnen helpen deed ik dat wel maar helaas geen ervaring in 
plugins.. Succes ermee. ik wacht er op!

Op 17-1-2016 om 21:38 schreef Petertjuh360:

**Comment by comput1q** [comment]
nu heb ik deze error

Warning: 
require(/usr/local/directadmin/plugins/da-letsencrypt/vendor/amphp/amp/lib/functions.php): 
failed to open stream: No such file or directory in 
/usr/local/directadmin/plugins/da-letsencrypt/vendor/composer/autoload_real.php 
on line 55 Fatal error: require(): Failed opening required 
'/usr/local/directadmin/plugins/da-letsencrypt/vendor/amphp/amp/lib/functions.php' 
(include_path='.:/usr/local/lib/php') in 
/usr/local/directadmin/plugins/da-letsencrypt/vendor/composer/autoload_real.php 
on line 55

Op 17-1-2016 om 21:39 schreef Wouter van Os:

**Comment by ghost** [comment]
@comput1q 

The best thing you can do right now is to wait for the final release of the plugin. At that moment everything should work properly.

NL: Het beste dat je nu kunt doen is wachten tot het moment dat de plugin stabiel en officieel uitgebracht is, dan zou alles goed moeten werken.
