### ISSUE TITLE
Great, some problems

### ISSUE THREAD

**Issue by kloentje2** [Petertjuh360/da-letsencrypt#63]
I tried to issue a certificate for some domains and I get this error:
Error while completing domain challenges

Details

Exception while solving challenge for www.*****.**********.eu: selfVerify failed, please check http://www.*****.*********.eu/.well-known/acme-challenge/ijbY43KzCxAy9dlMDyt3I7SLk6-ysrLUX4kzEzxjq8g.

And others are working

(I am sorry for my bad English)

**Comment by zenire** [comment]
What does the page says when you visit the url?

**Comment by kloentje2** [comment]
404 not found

**Comment by Wouter0100** [comment]
When you visit http://www.*****.*********.eu/, do you see the index from your public_html?

**Comment by kloentje2** [comment]
Yes

**Comment by Wouter0100** [comment]
Strange. Did you try again?

**Comment by barryvdh** [comment]
Are you sure it's a regular 200 response directly, not a redirect (perhaps to version without www. or to https)?

**Comment by kloentje2** [comment]
I will try i again with some other domains...
