### ISSUE TITLE
Request fails if email does not match domain

### ISSUE THREAD

**Issue by Bramzor** [Petertjuh360/da-letsencrypt#66]
Apparently a request fails if the email does not match the domain.
Might be an improvement to check this before sending the request?

**Comment by Wouter0100** [comment]
Hmm, does it? Do you have any article/source where this is noted?

**Comment by Azerdion** [comment]
I tried to reproduce this; use an email address from a different domain when installing a certificate.
Result: I couldn't reproduce it. It installed the certificate successfully.

**Comment by zenire** [comment]
I couldn't reproduce it too. Email adresses from a different domain shouldn't matter.

**Comment by zenire** [comment]
Why do you think the request fails when the email domain does not match the domain @Bramzor  ?

**Comment by Bramzor** [comment]
For some reasons, it failed the first 2 times and it did work with the new email address. So my statement was indeed not valid. Although it failed for some still unknown reason.
