### ISSUE TITLE
Cron PHP Strict warning

### ISSUE THREAD

**Issue by zenire** [Petertjuh360/da-letsencrypt#67]
cron.php generates a PHP Strict warning:

PHP Strict Standards: Only variables should be passed by reference in /usr/local/directadmin/plugins/da-letsencrypt/scripts/cron.php on line 111
PHP Strict Standards: Only variables should be passed by reference in /usr/local/directadmin/plugins/da-letsencrypt/scripts/cron.php on line 112

Lees meer: Re: le plugin - webhostingtalk.nl http://www.webhostingtalk.nl/private.php#ixzz3x9X2l42x

**Comment by Wouter0100** [comment]
Is this recent? Since [line 112](https://github.com/Petertjuh360/da-letsencrypt/blob/471b5344663ca4449205c4161e9f8eb030e1cfdc/scripts/cron.php#L112) is empty.

**Comment by zenire** [comment]
Must be line 110 and line 111 now after the removal of the http restart. Let me check.

**Comment by zenire** [comment]
Is indeed about the current line 110 and 111.

**Comment by barryvdh** [comment]
Yeah you can't pass an function to array_pop, you have to create a local variable first.
https://3v4l.org/oD6CZ

**Comment by Wouter0100** [comment]
Ah, good point. Hmm.

**Comment by Wouter0100** [comment]
This has been fixed by #68.
