### ISSUE TITLE
Keys saved but not registered at server

### ISSUE THREAD

**Issue by Wouter0100** [Petertjuh360/da-letsencrypt#7]
When you switch between servers (staging/live for example) the account keys are saved locally, so reused. But they aren't know at the server, so the server response with an error that the key isn't registered yet.

**Comment by Wouter0100** [comment]
In order to delete all locally stored account keys, we need access to all user's folders, which we can't get.. Or do I miss something here?

**Comment by zenire** [comment]
What you basically mean is we need to push the locally saved keys again to the live Let's Encrypt server but we can't acces these locally saved keys?

**Comment by barryvdh** [comment]
Can't you store for which server each key is used, so both accounts can be stored together?

**Comment by Wouter0100** [comment]
We could create a directory with the name of the server (api-v01.letsen....) and place the keys in there. On this way we could split everything nice. Or just "live", "staging" and "custom".

**Comment by zenire** [comment]
That would be a nice solution. I think "live", "staging" and "custom" are better. When api-v01 is updates to api-v02 for example, you would need to change the directory etc.

**Comment by Wouter0100** [comment]
That's true. But then you have the same issue, but only when you change the custom server from one to another.

**Comment by zenire** [comment]
We can move the keys between the folders and push them to the server when the custom value of the server value changes.

This way (when using the live, staging and custom folders) we only have three folders and can't make a mess (for each custom value a new folder).
