### ISSUE TITLE
That plugin does not exist for the specified User Level

### ISSUE THREAD

**Issue by hantk8** [Petertjuh360/da-letsencrypt#71]
I installed the plugin on my test vps but it does not show up in directadmin
when i try to acces through the url http://mydomain.com:2222/CMD_PLUGINS_ADMIN/da-letsencrypt/index.html 
i get
"That plugin does not exist for the specified User Level"

My config is

Apache 2.4.17
DirectAdmin 1.49.1
Exim 4.84
MySQL 5.5.31
Named 9.8.2rc1
sshd
dovecot 2.2.19
pure-ftpd 1.0.42
Php 5.5.30

any suggestions?

**Comment by Wouter0100** [comment]
Is the plugin activated and installed?

**Comment by hantk8** [comment]
![screen shot 2016-01-21 at 17 28 09](https://cloud.githubusercontent.com/assets/16821341/12486788/7373391a-c064-11e5-8ba9-db3a8e87471b.png)

Yes it installed and active (see attached screenshot)

**Comment by Wouter0100** [comment]
Hmm, maybe there is a conflict? Remove the master one.

**Comment by hantk8** [comment]
Removed the master
deactivated & reactivated 

deactivated CSF 

unfortunately still not working...

**Comment by Wouter0100** [comment]
Is the `index.html` present in the users folder?

**Comment by hantk8** [comment]
can you give the path to the folder?
Which users folder do you mean?

**Comment by Wouter0100** [comment]
The users folder of this plugin.

**Comment by hantk8** [comment]
There is no users folder in the plug-in folder

**Comment by Wouter0100** [comment]
`user`, excuus me. But that is the issue. Please remove the plugin and try cloning again.

**Comment by hantk8** [comment]
I'll try that first thing tomorrow.

Thanks

**Comment by hantk8** [comment]
reinstalled the plugin and its working now. thanks
Still some issues but i will start a new topic
