### ISSUE TITLE
Can't save certificate

### ISSUE THREAD

**Issue by v0112358** [Petertjuh360/da-letsencrypt#74]
Hello,

I'm testing your module and I found that your module can't save certificate into /usr/local/direcadmin/data/users/USERNAME/domains/DOMAIN. The error messages:

Error while saving SSL certificates to DirectAdmin

Details

Successfully completed challenge for DOMAIN.
Successfully received certificate from Let's Encrypt.
Error while executing first API request: You can only add a certificate if you own the ip you are using 

I'm using CentOS 6.7 64 bit (Support SNI), Cloudlinux, php version 5.5 and one IP for all account.

I hope you do solve this issue soon.

Thanks

**Comment by Wouter0100** [comment]
Error message says it all. `You can only add a certificate if you own the ip you are using`. Plugin currently only supports SNI. An error message for this is already planned in #38.
