### ISSUE TITLE
Is there a manual?

### ISSUE THREAD

**Issue by janw-me** [Petertjuh360/da-letsencrypt#78]
I installed it. But I'm having problems.  So is there a manual or documentation? The wiki is empty.

To sum up my questions, maybe there are simple explanations or other issues
1. When I setup a second domain the first one stops working. The error says the certificate is only valid for the second domain.
2. How can I apply a certificate to the Direct Admin port (2222)? It kind of defeats the purpose to secure a site but have a insecure control panel.
3. How can I apply a certificate to the email subdomains? _mail_, _smtp_.
4. Do I need to setup an extra cronjob? The [wiki page](https://github.com/Petertjuh360/da-letsencrypt/wiki/View-cronjob-configuration) is empty.
5. What does the 'ACME server' do? I installed it on a live/production VPS so I selected _'Let's Encrypt Live'_

Thanks in advance. Love what you guys are doing here.

**Comment by zenire** [comment]
Hi,

Thank you for your message!

Read the README, please. Active development stopped. There is an instruction in the README.

**Comment by janw-me** [comment]
Oh Sorry, I skipped over that part....  
Can I just remove the plugin files or is there anything else I need to do to correctly remove it?

**Comment by Wouter0100** [comment]
You should remove it through DirectAdmin, then it also correctly removes things like the cronjob.

**Comment by kloentje2** [comment]
DirectAdmin also has a own feauture to use Let's Encrypt...

http://www.directadmin.com/features.php?id=1828

**Comment by Wouter0100** [comment]
That's already mentioned in the `README.md` and that's why the plugin development has been stopped.

Please keep in mind that the DirectAdmin Let's Encrypt is also still in BETA, so NOT recommended in production.
