### ISSUE TITLE
da-letsencrypt don't support custom DA port

### ISSUE THREAD

**Issue by v0112358** [Petertjuh360/da-letsencrypt#79]
Hello,

When DA is running on port 8888 then da-letsencrypt can't connect to DA API. It's show warning "Warning: stream_socket_client(): unable to connect to 127.0.0.1:2222 (Connection refused) in /usr/local/directadmin/plugins/da-letsencrypt/includes/lib/HTTPSocket.php on line 198".

**Comment by Wouter0100** [comment]
Plugin development is discontinued as mentioned in the `README`. It's now officially supported (beta) by DirectAdmin (1.50).
