### ISSUE TITLE
Cronjob for reissue

### ISSUE THREAD

**Issue by Wouter0100** [Petertjuh360/da-letsencrypt#8]
We'll need to run a cronjob for reissuing a SSL certificate.

**Comment by AramVK** [comment]
What would be a good way to store the domains being used for Let's encrypt and therefore need to be renewed?
If DA doesn't have a database like system inbuilt maybe something like sqlite. This could also be used to store other dynamic/configurable data.

**Comment by Wouter0100** [comment]
True, currently I had in mind to loop through all domains for the .letsencrypt folder. On this way, when an user moves between server(s) or Directadmin installations using Directadmin backups, the state of the plugin is saved and the cron knows that it needs to be reissued. 

As "storage" just a JSON file or something.

**Comment by Wouter0100** [comment]
Implemented.
