### ISSUE TITLE
error on update

### ISSUE THREAD

**Issue by pljvp** [Petertjuh360/da-letsencrypt#80]
Hi,

:: LE mailed me:
"Your certificate (or certificates) for the names listed below will expire in 10 days (on 10 May 16 20:08 +0000). Please make sure to renew your certificate before then, or visitors to your website will encounter errors."

:: So I opened my DA, showing:
SSL information
Account status  Not generated yet
Account keys    Generated (view / edit)
Request a (new) SSL certificate
Domain  MYDOMAINNAME.com
Subdomains  www.MYDOMAINNAME.com
mg.MYDOMAINNAME.com
www.mg.MYDOMAINNAME.com
E-mail Address  (e.g. example@domain.com)
I accept the Terms of Service of Let's Encrypt.
Plugin is created by Wouter van Os (Wouter0100), Peter Bin (Petertjuh360) and all it's contributors. 

:: I Completed the emailadres with:
hello@MYDOMAINNAME.com 
and pressed [ submit query ] 

:: I get this error:
Warning: openssl_pkey_get_details() expects parameter 1 to be resource, boolean given in /usr/local/directadmin/plugins/da-letsencrypt/vendor/kelunik/acme/lib/AcmeClient.php on line 165
Error while completing domain challenges
Details
Only RSA keys are supported right now. 

DA does't let me update.
1) how to make my account status 'generated' instead of 'not generated yet'?
2) update LE once and for all ;-)

**Comment by Wouter0100** [comment]
```
Development of this plugin is suspended because of native Let's Encrypt support in DirectAdmin since version 1.49.2.
```

If this features isn't being released or very limited, we'll continue development.

**Comment by zenire** [comment]
Also see: https://www.directadmin.com/features.php?id=1828

**Comment by pljvp** [comment]
Thank you!
