### ISSUE TITLE
Install under DirectAdmin v1.51.4

### ISSUE THREAD

**Issue by kenzie-wu** [Petertjuh360/da-letsencrypt#81]
[root@f32 plugins]# composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer could not find a composer.json file in /usr/local/directadmin/plugins
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

What is the problem with the implementation of this step?

**Comment by v998** [comment]
seems you are not in the `da-letsencrypt` directory

also please be reminded that this plugin is no longer actively developed because there is already native support for Let's Encrypt from DirectAdmin officially

**Comment by zenire** [comment]
This project is discontinued because of the official support from DirectAdmin as @v998 says indeed. https://help.directadmin.com/item.php?id=648
