### ISSUE TITLE
Create option to switch server

### ISSUE THREAD

**Issue by Wouter0100** [Petertjuh360/da-letsencrypt#9]
In the admin (and maybe reseller?) level we need to create a option/value to define the used server. Defaults to live (api-01), but we should be able to overwrite this.

**Comment by zenire** [comment]
Where should we store the value for this option? Shall we use the plugin.conf (which DirectAdmin uses mainly) or create an own .conf file?

**Comment by Wouter0100** [comment]
I'm not a fan of overwriting files saved in github and not defined in `.gitignore` (because of the "own work" when pulling updates using git). I'm not sure what we should use for this tho, I think the best option is to use the plugin.conf, yeah..

**Comment by zenire** [comment]
I am sorry, I lost track with "I'm not a fan of overwriting files saved in github and not defined in .gitignore". What do you mean?

**Comment by zenire** [comment]
Let's use the plugin.conf

**Comment by zenire** [comment]
Also see 196f2a0c000420381c5608c67972f7bf21ea33ba

**Comment by Wouter0100** [comment]
Hmm, yeah, maybe not a "live=yes", but more a "acmeServer=https://acme-v01.api.letsencrypt.org/"? On this way sysadmins should also be able to define other servers (this is only for advanced users, since by default it should be the live one of Lets Encrypt)

**Comment by zenire** [comment]
Yes, let's define the acmeServer in the plugin.conf and add a feature in the plugin with following options:
1. Live (sets the server you provided in your comment)
2. Test (sets the test server)
3. Custom (sets a server that the admin provides)

Do you agree with this? This way we have an user friendly option but it can also be used for advanced users.

**Comment by Wouter0100** [comment]
Hmm,  awesome. Let's do that.
